FROM nvidia/cuda:12.6.1-base-ubuntu22.04
#set bash as default shell
SHELL ["/bin/bash", "-c"]
# install ros2 humble

RUN apt update && sudo apt install locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8

RUN apt install software-properties-common
RUN add-apt-repository universe

RUN apt update && sudo apt install curl -y
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt-get update -y\
    && apt-get upgrade -y \
    && apt-get install -y ros-humble-desktop-full


COPY .bashrc home/ubuntu/.bashrc
RUN source home/ubuntu/.bashrc

# install coppeliasim
RUN apt-get update -y \
    && apt-get install python3-colcon-common-extensions \
    && apt-get install -y python3-pip \
    && pip3 install -U setuptools==58.0.2 \ 
    && apt-get install -y git \
    && apt-get install -y gedit \
    && apt-get install -y wget \
    && apt-get install -y libgl1-mesa-glx \
    && apt-get install xsltproc \
    && apt-get install -y --no-install-recommends \
        vim tar xz-utils \
        libx11-6 libxcb1 libxau6 libgl1-mesa-dev \
        xvfb dbus-x11 x11-utils libxkbcommon-x11-0 \
        libavcodec-dev libavformat-dev libswscale-dev \
        python3.10 python3-pip libraw1394-11 libmpfr6 \
        libusb-1.0-0

RUN pip3 install pyzmq cbor2 xmlschema

# install coppeliasim
USER ubuntu
    WORKDIR /home/ubuntu
        RUN wget https://downloads.coppeliarobotics.com/V4_9_0_rev6/CoppeliaSim_Edu_V4_9_0_rev6_Ubuntu22_04.tar.xz
        RUN tar -xvf CoppeliaSim_Edu_V4_9_0_rev6_Ubuntu22_04.tar.xz
        RUN git clone https://github.com/Shell-Urban-Concept-Autonomous/shell_urban_simulator.git
        WORKDIR /home/ubuntu/shell_urban_simulator
            RUN colcon build --symlink-install
            RUN echo "source /home/ubuntu/shell_urban_simulator/install/setup.bash" >> /home/ubuntu/.bashrc 
